### ISSUE TITLE
Setup deployment pilepline

### ISSUE THREAD

**Issue by SanJSp** [bptlab/ark_automate#12]
As a Team, we'd like to set up our deployment pipeline.

---

### :thought_balloon: Hints & Thoughts
Concerns Github and heroku
### :question: Additional Questions to Answer / Consider

---

## :white_check_mark: Conditions of satisfaction

- [ ] On push to branch `master` new version is being deployed

**Comment by kej-jay** [comment]
As far as I can tell there are issues with our deployment because of the use of react router. Please see [this Link](https://create-react-app.dev/docs/deployment/) to learn more about it.
After that, setting up deployment should be fairly easy.

**Comment by kej-jay** [comment]
```
on:
  push:
    branches:
      - DEV
  workflow_dispatch:
name: Heroku Deployment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy server to root and commit
        run: |
          mv ./server/* ./
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Heroku Deployer
          author_email: heroku.deployer@ark-automate.com
          message: "heroku deployment commit"
          push: false
      - uses: akhileshns/heroku-deploy@v3.11.10
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ark-automate"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
```
